// Generated by https://quicktype.io

export interface Person {
  nombrecompleto: string;
  email:          string;
  password:       string;
  telefono:       string;
  updatedAt:     string;
  createdAt:     string;
  id:             number;
}
